global using MediatR;
global using Microsoft.Extensions.DependencyInjection;
global using ToDoApp.Bll.Exceptions;
global using ToDoApp.Bll.Mapping;
global using ToDoApp.Bll.Models.Commands;
global using ToDoApp.Bll.Models.Queries;
global using ToDoApp.Bll.Models.Results;
global using ToDoApp.Bll.Storage.Dtos;
global using ToDoApp.Bll.Storage.Interfaces;
