global using System.Net.Http.Json;
global using DotNet.Testcontainers.Builders;
global using DotNet.Testcontainers.Containers;
global using DotNet.Testcontainers.Images;
global using FluentAssertions;
global using Testcontainers.MongoDb;
global using ToDoApp.Api.Contracts.Requests;
global using ToDoApp.Api.Contracts.Responses;
global using Xunit;
