global using AutoMapper;
global using FluentValidation;
global using FluentValidation.AspNetCore;
global using MediatR;
global using Microsoft.AspNetCore.Mvc;
global using Microsoft.AspNetCore.Mvc.Filters;
global using Microsoft.AspNetCore.Mvc.ModelBinding;
global using ToDoApp.Api.Contracts.Requests;
global using ToDoApp.Api.Contracts.Responses;
global using ToDoApp.Api.Controllers;
global using ToDoApp.Api.Extensions;
global using ToDoApp.Api.Filters;
global using ToDoApp.Api.Validation;
global using ToDoApp.Bll.Exceptions;
global using ToDoApp.Bll.Models.Commands;
global using ToDoApp.Bll.Models.Queries;
global using ToDoApp.Bll.Models.Results;
global using ToDoApp.Common.Mapping;

