name: Workaround to pass the required status check of the .NET CI workflow when it's not triggered

on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - backend/*

jobs:
  build-and-test:
    name: Build and test .NET projects
    runs-on: ubuntu-latest
    steps:
      - run: echo "Pass the required status check of the .NET CI workflow when it's not triggered"
