name: .NET CI

on:
  pull_request:
    branches:
      - master
    paths:
      - backend/**
      - .dockerignore 

jobs:
  build-and-test:
    name: Build and test .NET projects
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Build
        run: dotnet build /warnaserror

      - name: Test
        run: dotnet test --no-build
